#!/usr/bin/env python3
"""
phase_scramble_test_v2.py

Three-way phase control for multiplication-overlap remainder R.

Models
------
1. genuine
   The actual square-shell phase vector generated by the single integer n.

2. uniform
   For each odd prime p<=n choose an independent uniform residue r_p mod p.
   Preserves row density/period, destroys square-residue marginal and common n.

3. independent_square
   For each p choose u_p independently uniform mod p and set
       r_p = -(u_p^2 + delta) / 2 mod p,
   where delta=1 for even n, 2 for odd n, matching the first odd shell value
       lo_odd = n^2 + delta.
   This preserves the exact per-prime marginal law produced by a random square
   n^2 mod p, but destroys the cross-prime fact that all u_p come from one n.

Interpretation
--------------
uniform much worse, independent_square ~ genuine:
    suppression mainly from quadratic-residue marginals.

uniform ~ independent_square much worse than genuine:
    suppression mainly from cross-prime coherence of a common square.

independent_square intermediate:
    both effects matter.
"""

from __future__ import annotations

import argparse
import csv
import math
from concurrent.futures import ProcessPoolExecutor
from fractions import Fraction
from math import comb
from pathlib import Path
import numpy as np

G = {}


def primes_upto(n):
    s=np.ones(n+1,dtype=np.bool_); s[:2]=False
    for p in range(2,int(n**0.5)+1):
        if s[p]: s[p*p:n+1:p]=False
    a=np.nonzero(s)[0]
    return a[a>=3]


def lcm(a,b): return a//math.gcd(a,b)*b


def coeffs_P(K,r):
    D=1
    for j in range(K-1): D*=r+j
    vals=[]
    for w in range(K+1):
        z=w-1
        for j in range(K-1): z*=w-r-j
        vals.append(Fraction(1,1)+Fraction(z,D))
    out=[]; cur=vals
    for _ in range(K+1):
        out.append(cur[0])
        cur=[cur[i+1]-cur[i] for i in range(len(cur)-1)]
    return out


def elementary(primes,K):
    e=np.zeros(K+1); e[0]=1
    for p0 in primes:
        z=1/float(p0)
        for j in range(K,0,-1): e[j]+=z*e[j-1]
    return e


def setup(n,K,r,L):
    primes=primes_upto(n)
    coeff=coeffs_P(K,r)
    scale=1
    for c in coeff[1:]: scale=lcm(scale,c.denominator)
    point=np.zeros(65,dtype=np.int64)
    for w in range(65):
        Pw=sum(coeff[j]*comb(w,j) for j in range(1,K+1) if w>=j)
        point[w]=int((Fraction(1,1)-Pw)*scale)
    e=elementary(primes,K)
    cf=np.array([float(c) for c in coeff])
    M=float(sum(cf[j]*e[j] for j in range(1,K+1)))
    return primes,coeff,scale,point,e,M,L*(1-M)


def genuine_residues(n,primes):
    delta=1 if n%2==0 else 2
    lo=n*n+delta
    out=np.empty(len(primes),dtype=np.int64)
    for i,p0 in enumerate(primes):
        p=int(p0); inv2=(p+1)//2
        out[i]=(-(lo%p)*inv2)%p
    return out


def random_residues(mode,n,primes,rng):
    if mode=="uniform":
        return np.array([rng.integers(0,int(p)) for p in primes],dtype=np.int64)
    if mode=="independent_square":
        delta=1 if n%2==0 else 2
        out=np.empty(len(primes),dtype=np.int64)
        for i,p0 in enumerate(primes):
            p=int(p0)
            u=int(rng.integers(0,p))
            inv2=(p+1)//2
            out[i]=(-((u*u+delta)%p)*inv2)%p
        return out
    raise ValueError(mode)


def depth(n,primes,res):
    d=np.zeros(n,dtype=np.int16)
    for p0,r0 in zip(primes,res):
        d[int(r0)::int(p0)]+=1
    return d


def stats(d,L,point,scale,main_margin):
    s=point[d]
    pref=np.concatenate(([0],np.cumsum(s,dtype=np.int64)))
    cs=pref[L:]-pref[:-L]
    cert=cs.astype(float)/scale
    R=main_margin-cert
    i=int(np.argmax(R))
    q=np.quantile(R,[.5,.9,.99,.999])
    return {
        "max_R":float(R[i]),
        "min_certificate":float(cert[i]),
        "worst_start":i,
        "fail_windows":int(np.count_nonzero(cs<=0)),
        "R_median":float(q[0]),"R_q90":float(q[1]),
        "R_q99":float(q[2]),"R_q999":float(q[3]),
    }


def init_worker(n,K,r,L):
    primes,coeff,scale,point,e,M,mm=setup(n,K,r,L)
    G.update(n=n,K=K,r=r,L=L,primes=primes,scale=scale,point=point,
             main_margin=mm)


def trial(payload):
    mode,idx,seed=payload
    rng=np.random.default_rng(seed)
    res=random_residues(mode,G["n"],G["primes"],rng)
    d=depth(G["n"],G["primes"],res)
    x=stats(d,G["L"],G["point"],G["scale"],G["main_margin"])
    x.update(model=mode,trial=idx,seed=int(seed))
    return x


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--n",type=int,default=1_000_000)
    ap.add_argument("--K",type=int,default=5)
    ap.add_argument("--r",type=int,default=3)
    ap.add_argument("--window",type=int,default=391)
    ap.add_argument("--trials",type=int,default=100)
    ap.add_argument("--workers",type=int,default=2)
    ap.add_argument("--seed",type=int,default=20260831)
    ap.add_argument("--out",type=Path,default=Path("phase_scramble_threeway.csv"))
    args=ap.parse_args()

    primes,coeff,scale,point,e,M,mm=setup(args.n,args.K,args.r,args.window)
    gres=genuine_residues(args.n,primes)
    gst=stats(depth(args.n,primes,gres),args.window,point,scale,mm)

    ss=np.random.SeedSequence(args.seed)
    kids=ss.spawn(2*args.trials)
    payload=[]
    k=0
    for mode in ["uniform","independent_square"]:
        for i in range(1,args.trials+1):
            seed=int(kids[k].generate_state(1,dtype=np.uint64)[0]); k+=1
            payload.append((mode,i,seed))

    if args.workers==1:
        init_worker(args.n,args.K,args.r,args.window)
        rows=[trial(x) for x in payload]
    else:
        with ProcessPoolExecutor(max_workers=args.workers,initializer=init_worker,
            initargs=(args.n,args.K,args.r,args.window)) as ex:
            rows=list(ex.map(trial,payload,chunksize=1))

    args.out.parent.mkdir(parents=True,exist_ok=True)
    with args.out.open("w",newline="",encoding="utf-8") as f:
        wr=csv.DictWriter(f,fieldnames=list(rows[0].keys()))
        wr.writeheader(); wr.writerows(rows)

    print(f"n={args.n:,}, K={args.K}, r={args.r}, L={args.window}")
    print(f"M={M:.12f}, main margin={mm:.12f}")
    print(f"GENUINE max R={gst['max_R']:.12f}, min cert={gst['min_certificate']:.12f}, "
          f"fail windows={gst['fail_windows']}")
    print()

    for mode in ["uniform","independent_square"]:
        z=[x for x in rows if x["model"]==mode]
        a=np.array([x["max_R"] for x in z])
        fails=sum(x["fail_windows"]>0 for x in z)
        le=int(np.count_nonzero(a<=gst["max_R"]))
        p=(le+1)/(len(a)+1)
        print(mode.upper())
        print(f"  mean max R={a.mean():.12f}")
        print(f"  median max R={np.median(a):.12f}")
        print(f"  q01={np.percentile(a,1):.12f}")
        print(f"  q05={np.percentile(a,5):.12f}")
        print(f"  q95={np.percentile(a,95):.12f}")
        print(f"  failing realizations={fails}/{len(z)}")
        print(f"  max R <= genuine: {le}/{len(z)}, add-one p={p:.6g}")
        print()

    print(f"CSV: {args.out}")


if __name__=="__main__":
    main()
